# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do |lane, options|
    @build_type = "Debug"
    if not options.empty?
    @build_type = options[:release] ? "Release" : "Debug"
    end
  end


  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run instrumentation tests"
  lane :instrumentation_tests do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end

  desc "Run instrumentation tests in Firebase Test Lab"
  lane :instrumentation_tests_testlab do
    run_tests_firebase_testlab(
      project_id: "whereismybeartest",
      model: "Nexus6P",
      version: "28",
      delete_firebase_files: false)
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    gradle(task: "bundle", build_type: @build_type)
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do
    gradle(task: "assembleAndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble do
    assemble_build
    assemble_test_application
  end

 lane :beta do
   gradle(task: 'bundle', build_type: 'Release')
   upload_to_play_store(track: 'beta')
 end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end
